services:
  wyze-garmin-sync:
    build: .
    restart: unless-stopped
    environment:
      WYZE_EMAIL: ${WYZE_EMAIL}
      WYZE_PASSWORD: ${WYZE_PASSWORD}
      WYZE_KEY_ID: ${WYZE_KEY_ID}
      WYZE_API_KEY: ${WYZE_API_KEY}
      GARMIN_EMAIL: ${GARMIN_EMAIL}
      GARMIN_PASSWORD: ${GARMIN_PASSWORD}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./.garmin_tokens:/app/.garmin_tokens"
