version: "3.9"
services:
  wyzegarminconnect:
    image: svanhoutte/wyzegarminconnect:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      WYZE_EMAIL: "wyze username"
      WYZE_PASSWORD: "wyze password"
#go their to create your key and id https://developer-api-console.wyze.com/#/apikey/view
      WYZE_KEY_ID: "key_ID"
      WYZE_API_KEY: "api_key"
      Garmin_username: "garmin username"
      Garmin_password: "garmin password"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
